apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: titanium-project-refactored

build:
  local:
    push: false
  artifacts:
    # --- 신규 Go 서비스 ---
    - image: dongju101/titanium-lb    
      context: load-balancer
      docker:
        dockerfile: Dockerfile
    - image: dongju101/titanium-api   
      context: api-gateway
      docker:
        dockerfile: Dockerfile
        
    # --- FastAPI로 전환된 Python 서비스 ---
    - image: dongju101/titanium-auth-service
      context: auth-service
    - image: dongju101/titanium-user-service
      context: user-service
    - image: dongju101/titanium-blog-service
      context: blog-service
      
    # --- 변경 없는 UI ---
    - image: dongju101/titanium-ui
      context: dashboard-ui

manifests:
  kustomize:
    paths:
      - k8s-manifests/overlays/local
