apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: blog-service
build:
  local:
    push: false
  artifacts:
    - image: blog-service
      context: blog-service
manifests:
  rawYaml:
    - k8s-manifests/blog-service.yaml
