apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: titanium-base

resources:
- api-gateway-deployment.yaml
- api-gateway-service.yaml
- auth-service-deployment.yaml
- auth-service-service.yaml
- dashboard-ui-deployment.yaml
- dashboard-ui-service.yaml
- load-balancer-deployment.yaml
- load-balancer-service.yaml
- redis-deployment.yaml
- redis-service.yaml
- user-service-deployment.yaml
- user-service-service.yaml
- user-service-pvc.yaml
  # analytics-service 제거됨
- blog-service-deployment.yaml
- blog-service-service.yaml
- configmap.yaml
- secret.yaml
- user-service-backup-cronjob.yaml

# 기본 라벨만 간단히 적용
commonLabels:
  app.kubernetes.io/name: titanium
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  titanium.io/environment: base
