apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
  labels:
    app: load-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer-container
        image: dongju101/titanium-lb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7100
          name: http
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SERVICE_NAME
          value: "load-balancer"
        - name: SERVICE_PORT
          value: "7100"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /lb-health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /lb-health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5