apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: titanium
type: Opaque
data:
  # Base64 인코딩된 값들 (echo -n "값" | base64로 생성)
  
  # "api-secret-key" 인코딩
  INTERNAL_API_SECRET: YXBpLXNlY3JldC1rZXk=
  
  # "jwt-signing-key" 인코딩  
  JWT_SECRET_KEY: and0LXNpZ25pbmcta2V5
  
  # "redis-password" 인코딩
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=